ALTER TABLE route_stats
  DROP COLUMN IF EXISTS max_seconds,
  DROP COLUMN IF EXISTS p5,
  DROP COLUMN IF EXISTS p15,
  DROP COLUMN IF EXISTS p25,
  DROP COLUMN IF EXISTS p35,
  DROP COLUMN IF EXISTS p45,
  DROP COLUMN IF EXISTS p55,
  DROP COLUMN IF EXISTS p65,
  DROP COLUMN IF EXISTS p75,
  DROP COLUMN IF EXISTS p85,
  DROP COLUMN IF EXISTS p95;
